using System.Windows;
using System.Windows.Controls;
using YtDlpTool.Domain.Services;
using YtDlpTool.ViewModels;

namespace YtDlpTool.Views;

public partial class AdvancedOptionsView : UserControl
{
    private const int MaxSubtitles = 3;
    private MainViewModel? Vm => DataContext as MainViewModel;

    public AdvancedOptionsView()
    {
        InitializeComponent();
        DataContextChanged += OnDataContextChanged;
    }

    private void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
    {
        if (e.OldValue is MainViewModel oldVm) oldVm.PropertyChanged -= OnVmChanged;
        if (e.NewValue is MainViewModel newVm) newVm.PropertyChanged += OnVmChanged;
        RebuildSubtitles();
    }

    private void OnVmChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(MainViewModel.CurrentMetadata)) RebuildSubtitles();
        else if (e.PropertyName == nameof(MainViewModel.ClipRange)) SyncClipCheckboxFromVm();
    }

    /// <summary>
    /// Keeps the ClipEnabled checkbox in sync with the underlying ClipRange so the UI never
    /// shows a checked box while the VM has cleared the range (which happens automatically
    /// when the URL resolves to a different video — see MainViewModel.OnCurrentMetadataChanged).
    /// </summary>
    private void SyncClipCheckboxFromVm()
    {
        if (Vm is null) return;
        if (Vm.ClipRange is null && ClipEnabled.IsChecked == true)
        {
            ClipEnabled.IsChecked = false;
            ClipStart.IsEnabled = false;
            ClipEnd.IsEnabled = false;
            ClipError.Visibility = Visibility.Collapsed;
        }
    }

    private void RebuildSubtitles()
    {
        if (Vm is null || Vm.CurrentMetadata is null)
        {
            SubtitlesList.ItemsSource = Array.Empty<object>();
            SubtitleSection.Visibility = Visibility.Collapsed;
            return;
        }
        Vm.SelectedSubtitleLanguages.Clear();

        // Filter: keep only languages in the supported-display whitelist; when both manual
        // and auto-generated tracks exist for the same lang prefer the manual one; drop
        // the (auto) suffix in the rendered label.
        var byLang = new Dictionary<string, (string DisplayName, bool IsAuto)>(StringComparer.OrdinalIgnoreCase);
        foreach (var s in Vm.CurrentMetadata.Subtitles)
        {
            var display = SupportedSubtitles.GetDisplayName(s.LanguageCode);
            if (display is null) continue;
            // Manual (IsAutoGenerated = false) wins over auto for the same language code.
            if (!byLang.TryGetValue(s.LanguageCode, out var existing) || (existing.IsAuto && !s.IsAutoGenerated))
                byLang[s.LanguageCode] = (display, s.IsAutoGenerated);
        }

        var items = byLang
            .OrderBy(kv => kv.Value.DisplayName, StringComparer.Ordinal)
            .Select(kv => new CheckBox
            {
                Content = kv.Value.DisplayName,
                Tag = kv.Key,
                Margin = new Thickness(0, 0, 8, 4)
            })
            .ToList();
        foreach (var c in items)
        {
            c.Checked += OnSubtitleToggle;
            c.Unchecked += OnSubtitleToggle;
        }
        SubtitlesList.ItemsSource = items;
        SubtitleSection.Visibility = items.Count == 0 ? Visibility.Collapsed : Visibility.Visible;
    }

    private void OnSubtitleToggle(object sender, RoutedEventArgs e)
    {
        if (Vm is null) return;
        Vm.SelectedSubtitleLanguages.Clear();
        var checkedCount = 0;
        foreach (var item in SubtitlesList.Items)
        {
            if (item is CheckBox c && c.IsChecked == true && c.Tag is string lang)
            {
                if (checkedCount >= MaxSubtitles)
                {
                    c.IsChecked = false;
                    continue;
                }
                Vm.SelectedSubtitleLanguages.Add(lang);
                checkedCount++;
            }
        }
    }

    private void OnClipToggle(object sender, RoutedEventArgs e)
    {
        var enabled = ClipEnabled.IsChecked == true;
        ClipStart.IsEnabled = enabled;
        ClipEnd.IsEnabled = enabled;
        if (!enabled && Vm is not null) Vm.ClipRange = null;
        if (enabled) ApplyClip();
    }

    private void OnClipChanged(object sender, TextChangedEventArgs e)
    {
        if (ClipEnabled.IsChecked == true) ApplyClip();
    }

    private void ApplyClip()
    {
        if (Vm is null || Vm.CurrentMetadata is null) return;
        var r = TimeRangeValidator.Parse(ClipStart.Text, ClipEnd.Text, Vm.CurrentMetadata.Duration);
        if (!r.IsValid)
        {
            ClipError.Text = r.Reason!;
            ClipError.Visibility = Visibility.Visible;
            Vm.ClipRange = null;
            return;
        }
        ClipError.Visibility = Visibility.Collapsed;
        Vm.ClipRange = r.Range;
    }
}
