using System.Windows;
using System.Windows.Controls;
using YtDlpTool.Domain.Models;
using YtDlpTool.Domain.Services;
using YtDlpTool.Resources;
using YtDlpTool.ViewModels;

namespace YtDlpTool.Views;

public partial class AdvancedOptionsView : UserControl
{
    private const int MaxSubtitles = 3;
    private MainViewModel? Vm => DataContext as MainViewModel;

    public AdvancedOptionsView()
    {
        InitializeComponent();
        DataContextChanged += OnDataContextChanged;
    }

    private void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
    {
        if (e.OldValue is MainViewModel oldVm) oldVm.PropertyChanged -= OnVmChanged;
        if (e.NewValue is MainViewModel newVm) newVm.PropertyChanged += OnVmChanged;
        RebuildSubtitles();
    }

    private void OnVmChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(MainViewModel.CurrentMetadata)) RebuildSubtitles();
    }

    private void RebuildSubtitles()
    {
        if (Vm is null || Vm.CurrentMetadata is null)
        {
            SubtitlesList.ItemsSource = Array.Empty<object>();
            return;
        }
        Vm.SelectedSubtitleLanguages.Clear();
        var items = Vm.CurrentMetadata.Subtitles.Select(s => new CheckBox
        {
            Content = s.DisplayName + (s.IsAutoGenerated ? Strings.Get("Advanced.SubtitlesAutoSuffix") : ""),
            Tag = s.LanguageCode,
            Margin = new Thickness(0, 0, 8, 4)
        }).ToList();
        foreach (var c in items)
        {
            c.Checked += OnSubtitleToggle;
            c.Unchecked += OnSubtitleToggle;
        }
        SubtitlesList.ItemsSource = items;
    }

    private void OnSubtitleToggle(object sender, RoutedEventArgs e)
    {
        if (Vm is null) return;
        Vm.SelectedSubtitleLanguages.Clear();
        var checkedCount = 0;
        foreach (var item in SubtitlesList.Items)
        {
            if (item is CheckBox c && c.IsChecked == true && c.Tag is string lang)
            {
                if (checkedCount >= MaxSubtitles)
                {
                    c.IsChecked = false;
                    continue;
                }
                Vm.SelectedSubtitleLanguages.Add(lang);
                checkedCount++;
            }
        }
    }

    private void OnClipToggle(object sender, RoutedEventArgs e)
    {
        var enabled = ClipEnabled.IsChecked == true;
        ClipStart.IsEnabled = enabled;
        ClipEnd.IsEnabled = enabled;
        if (!enabled && Vm is not null) Vm.ClipRange = null;
        if (enabled) ApplyClip();
    }

    private void OnClipChanged(object sender, TextChangedEventArgs e)
    {
        if (ClipEnabled.IsChecked == true) ApplyClip();
    }

    private void ApplyClip()
    {
        if (Vm is null || Vm.CurrentMetadata is null) return;
        var r = TimeRangeValidator.Parse(ClipStart.Text, ClipEnd.Text, Vm.CurrentMetadata.Duration);
        if (!r.IsValid)
        {
            ClipError.Text = r.Reason!;
            ClipError.Visibility = Visibility.Visible;
            Vm.ClipRange = null;
            return;
        }
        ClipError.Visibility = Visibility.Collapsed;
        Vm.ClipRange = r.Range;
    }
}
