using System.Text.Json;
using YtDlpTool.Domain.Models;

namespace YtDlpTool.Process;

public sealed class YtDlpRunner
{
    private readonly string _executable;

    public YtDlpRunner(string executable)
    {
        _executable = executable;
    }

    public async Task<MetadataFetchResult> FetchMetadataAsync(
        string url,
        CancellationToken cancellationToken = default)
    {
        var args = new ProcessStartArguments(
            ExecutablePath: _executable,
            Arguments: new[]
            {
                "--dump-single-json",
                "--no-playlist",
                "--no-warnings",
                "--",
                url
            },
            Timeout: TimeSpan.FromSeconds(30));

        var stdoutLines = new List<string>();
        var exit = await ProcessSandbox.RunAsync(args,
            onStdout: line => stdoutLines.Add(line.Text),
            cancellationToken: cancellationToken);

        if (exit.ExitCode != 0 || exit.TimedOut || exit.Cancelled)
            return new MetadataFetchResult(false, null, exit.Stderr);

        var raw = string.Join('\n', stdoutLines);
        YtDlpMetadataDto? dto;
        try
        {
            dto = JsonSerializer.Deserialize(raw, YtDlpJsonContext.Default.YtDlpMetadataDto);
        }
        catch (JsonException)
        {
            return new MetadataFetchResult(false, null, "JSON parse failed");
        }

        if (dto is null || string.IsNullOrEmpty(dto.Id) || string.IsNullOrEmpty(dto.Title))
            return new MetadataFetchResult(false, null, "missing fields");

        return new MetadataFetchResult(true, MapToMetadata(dto), null);
    }

    private static VideoMetadata MapToMetadata(YtDlpMetadataDto dto)
    {
        var formats = (dto.Formats ?? Array.Empty<YtDlpFormatDto>())
            .Select(f => new VideoFormat(
                FormatId: f.FormatId ?? "",
                Height: f.Height,
                VideoCodec: f.Vcodec is null or "none" ? null : f.Vcodec,
                AudioCodec: f.Acodec is null or "none" ? null : f.Acodec,
                Extension: f.Ext ?? "",
                FileSizeBytes: f.Filesize ?? f.FilesizeApprox,
                AudioBitrateKbps: f.Abr.HasValue ? (int)Math.Round(f.Abr.Value) : null))
            .ToList();

        var subtitles = new List<SubtitleTrack>();
        if (dto.Subtitles is not null)
            foreach (var kv in dto.Subtitles)
                subtitles.Add(new SubtitleTrack(kv.Key, kv.Key, IsAutoGenerated: false));
        if (dto.AutomaticCaptions is not null)
            foreach (var kv in dto.AutomaticCaptions)
                if (!subtitles.Any(s => s.LanguageCode == kv.Key))
                    subtitles.Add(new SubtitleTrack(kv.Key, kv.Key + " (auto)", IsAutoGenerated: true));

        return new VideoMetadata(
            VideoId: dto.Id ?? "",
            Title: dto.Title ?? "",
            Channel: dto.Uploader ?? "",
            Duration: TimeSpan.FromSeconds(dto.Duration ?? 0),
            ThumbnailUrl: dto.Thumbnail ?? "",
            Formats: formats,
            Subtitles: subtitles);
    }
}
