using System.Text.Json;
using YtDlpTool.Domain.Models;

namespace YtDlpTool.Process;

public sealed class YtDlpRunner
{
    private readonly string _executable;

    public YtDlpRunner(string executable)
    {
        _executable = executable;
    }

    public async Task<MetadataFetchResult> FetchMetadataAsync(
        string url,
        CancellationToken cancellationToken = default)
    {
        var fetchArgs = new List<string>
        {
            "--dump-single-json",
            "--no-playlist",
            "--no-warnings",
        };
        AddSystemProxyArgs(fetchArgs);
        fetchArgs.Add("--");
        fetchArgs.Add(url);

        var args = new ProcessStartArguments(
            ExecutablePath: _executable,
            Arguments: fetchArgs,
            Timeout: TimeSpan.FromSeconds(30));

        var stdoutLines = new List<string>();
        var exit = await ProcessSandbox.RunAsync(args,
            onStdout: line => stdoutLines.Add(line.Text),
            cancellationToken: cancellationToken);

        if (exit.ExitCode != 0 || exit.TimedOut || exit.Cancelled)
            return new MetadataFetchResult(false, null, exit.Stderr);

        var raw = string.Join('\n', stdoutLines);
        YtDlpMetadataDto? dto;
        try
        {
            dto = JsonSerializer.Deserialize(raw, YtDlpJsonContext.Default.YtDlpMetadataDto);
        }
        catch (JsonException)
        {
            return new MetadataFetchResult(false, null, "JSON parse failed");
        }

        if (dto is null || string.IsNullOrEmpty(dto.Id) || string.IsNullOrEmpty(dto.Title))
            return new MetadataFetchResult(false, null, "missing fields");

        return new MetadataFetchResult(true, MapToMetadata(dto), null);
    }

    private static VideoMetadata MapToMetadata(YtDlpMetadataDto dto)
    {
        var formats = (dto.Formats ?? Array.Empty<YtDlpFormatDto>())
            .Select(f => new VideoFormat(
                FormatId: f.FormatId ?? "",
                Height: f.Height,
                VideoCodec: f.Vcodec is null or "none" ? null : f.Vcodec,
                AudioCodec: f.Acodec is null or "none" ? null : f.Acodec,
                Extension: f.Ext ?? "",
                FileSizeBytes: f.Filesize ?? f.FilesizeApprox,
                AudioBitrateKbps: f.Abr.HasValue ? (int)Math.Round(f.Abr.Value) : null))
            .ToList();

        var subtitles = new List<SubtitleTrack>();
        if (dto.Subtitles is not null)
            foreach (var kv in dto.Subtitles)
                subtitles.Add(new SubtitleTrack(kv.Key, kv.Key, IsAutoGenerated: false));
        if (dto.AutomaticCaptions is not null)
            foreach (var kv in dto.AutomaticCaptions)
                if (!subtitles.Any(s => s.LanguageCode == kv.Key))
                    subtitles.Add(new SubtitleTrack(kv.Key, kv.Key + " (auto)", IsAutoGenerated: true));

        return new VideoMetadata(
            VideoId: dto.Id ?? "",
            Title: dto.Title ?? "",
            Channel: dto.Uploader ?? "",
            Duration: TimeSpan.FromSeconds(dto.Duration ?? 0),
            ThumbnailUrl: dto.Thumbnail ?? "",
            Formats: formats,
            Subtitles: subtitles);
    }

    public async Task<DownloadResult> DownloadAsync(
        DownloadRequest request,
        IProgress<ProgressReport>? progress = null,
        CancellationToken cancellationToken = default)
    {
        var argList = new List<string>();
        argList.AddRange(BuildFormatArgs(request));
        argList.AddRange(new[]
        {
            "--newline",
            "--progress-template",
            "[download] {\"percent\":%(progress._percent_str)s,\"speed\":\"%(progress._speed_str)s\",\"eta\":\"%(progress._eta_str)s\"}",
            "--no-playlist",
            "--no-warnings",
            // Resilience against transient YouTube rate-limit hits and CDN hiccups —
            // particularly important for --download-sections which makes more range
            // requests per minute than a normal full download.
            "--retries", "10",
            "--fragment-retries", "10",
            "--retry-sleep", "5",
            "--output",
            BuildOutputTemplate(request),
        });
        argList.AddRange(BuildSubtitleArgs(request));
        argList.AddRange(BuildClipArgs(request));
        argList.AddRange(BuildFfmpegLocationArgs());
        AddSystemProxyArgs(argList);
        if (request.EmbedThumbnail) argList.Add("--embed-thumbnail");
        if (request.ForceOverwrite) argList.Add("--force-overwrites");
        argList.Add("--");
        argList.Add(request.Url);

        var args = new ProcessStartArguments(
            ExecutablePath: _executable,
            Arguments: argList);

        string? finalPath = null;
        var exit = await ProcessSandbox.RunAsync(args,
            onStdout: line => ParseProgress(line.Text, progress, ref finalPath),
            cancellationToken: cancellationToken);

        if (exit.Cancelled) return new DownloadResult(false, null, exit.Stderr, true);
        if (exit.ExitCode != 0) return new DownloadResult(false, null, exit.Stderr, false);
        return new DownloadResult(true, finalPath, null, false);
    }

    private static IEnumerable<string> BuildFormatArgs(DownloadRequest r)
    {
        return r.Mode switch
        {
            DownloadMode.AudioOnly =>
                new[] { "-f", r.ChosenFormat.FormatId, "-x", "--audio-format", InferAudioFormat(r.ChosenFormat) },
            DownloadMode.VideoOnly =>
                new[] { "-f", r.ChosenFormat.FormatId },
            DownloadMode.AudioAndVideo =>
                new[] { "-f", $"{r.ChosenFormat.FormatId}+bestaudio", "--merge-output-format", "mp4" },
            _ => Array.Empty<string>()
        };
    }

    private static string InferAudioFormat(VideoFormat f) =>
        (f.Extension is "m4a" or "mp4") ? "m4a" : "mp3";

    private static IEnumerable<string> BuildSubtitleArgs(DownloadRequest r)
    {
        if (r.Mode == DownloadMode.AudioOnly) yield break;
        if (r.SubtitleLanguageCodes.Count == 0) yield break;
        // When clipping, skip subtitles entirely. yt-dlp downloads subtitles for the
        // full-length video and tries to embed them into the trimmed media, producing
        // mistimed captions. The extra subtitle download also seems to push us over
        // YouTube's rate-limit threshold mid-section more often than without.
        // If the user wants subtitles on a clip, they can clip first then re-download
        // with subtitles only on the full video.
        if (r.ClipRange is not null) yield break;
        yield return "--write-subs";
        yield return "--write-auto-subs";
        yield return "--sub-langs";
        yield return string.Join(',', r.SubtitleLanguageCodes);
        yield return "--embed-subs";
    }

    // Internal-visible so tests in YtDlpTool.Process.Tests can assert the arg list
    // shape for both video and audio clip modes (Fix 9 / v1.1.6 clip-success fix).
    internal static IEnumerable<string> BuildClipArgs(DownloadRequest r)
    {
        if (r.ClipRange is null) yield break;
        yield return "--download-sections";
        yield return r.ClipRange.ToYtDlpFormat();
        // --force-keyframes-at-cuts removed (v1.1.6): it required a re-encode around
        // the cut points which silently failed on many format combinations, leaving
        // only sidecar files (.vtt / .jpg / .webp) next to a missing media file while
        // yt-dlp still exited 0. The cut may land on the nearest keyframe instead of
        // the exact second, but the file actually gets produced. Frame-precise
        // cutting is deferred to a future version.
    }

    /// <summary>
    /// Fix D: managed environments almost always have a corporate HTTP proxy configured
    /// in the Internet Settings hive. yt-dlp's urllib doesn't read WinHTTP, so we
    /// pass the detected proxy URL via --proxy here. No-op when no proxy is set.
    /// </summary>
    private static void AddSystemProxyArgs(List<string> argList)
    {
        var systemProxy = SystemProxy.DetectHttpProxy();
        if (!string.IsNullOrEmpty(systemProxy))
        {
            argList.Add("--proxy");
            argList.Add(systemProxy);
        }
    }

    /// <summary>
    /// Tell yt-dlp explicitly where to find ffmpeg.exe. We can't rely on the working
    /// directory or PATH because the app runs from a single-file extracted location that
    /// is NOT on PATH. Without this, clip extraction + audio re-mux can silently fail
    /// with "ffmpeg not found" inside the user's clip output.
    /// </summary>
    private IEnumerable<string> BuildFfmpegLocationArgs()
    {
        var ffmpegPath = Path.Combine(Path.GetDirectoryName(_executable) ?? "", "ffmpeg.exe");
        if (File.Exists(ffmpegPath))
        {
            yield return "--ffmpeg-location";
            yield return ffmpegPath;
        }
    }

    private static string BuildOutputTemplate(DownloadRequest r)
    {
        return Path.Combine(r.SaveDirectory, r.SanitizedFileStem + ".%(ext)s");
    }

    private static readonly System.Text.RegularExpressions.Regex DestinationRegex =
        new(@"\[download\]\s+Destination:\s*(?<path>.+)$", System.Text.RegularExpressions.RegexOptions.Compiled);
    private static readonly System.Text.RegularExpressions.Regex ProgressJsonRegex =
        new(@"\{""percent""\s*:\s*""?(?<pct>[\d.]+)%?""?[^}]*""speed""\s*:\s*""(?<speed>[^""]+)""[^}]*""eta""\s*:\s*""(?<eta>[^""]+)""\}",
            System.Text.RegularExpressions.RegexOptions.Compiled);

    private static void ParseProgress(string line, IProgress<ProgressReport>? progress, ref string? finalPath)
    {
        var destMatch = DestinationRegex.Match(line);
        if (destMatch.Success) finalPath = destMatch.Groups["path"].Value.Trim();

        if (progress is null) return;
        var m = ProgressJsonRegex.Match(line);
        if (!m.Success) return;
        if (!double.TryParse(m.Groups["pct"].Value, System.Globalization.NumberStyles.Float,
            System.Globalization.CultureInfo.InvariantCulture, out var pct)) return;
        var bps = ParseSpeed(m.Groups["speed"].Value);
        var eta = ParseEta(m.Groups["eta"].Value);
        progress.Report(new ProgressReport(pct, bps, eta));
    }

    private static long? ParseSpeed(string s)
    {
        // "5.2MiB/s" / "512KiB/s" / "Unknown"
        var match = System.Text.RegularExpressions.Regex.Match(s,
            @"(?<v>[\d.]+)\s*(?<u>[KMGT]?i?B)/s", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        if (!match.Success) return null;
        if (!double.TryParse(match.Groups["v"].Value, System.Globalization.NumberStyles.Float,
            System.Globalization.CultureInfo.InvariantCulture, out var v)) return null;
        var unit = match.Groups["u"].Value.ToUpperInvariant();
        return (long)(v * unit switch
        {
            "KIB" => 1024.0, "KB" => 1000.0,
            "MIB" => 1024.0 * 1024, "MB" => 1_000_000.0,
            "GIB" => 1024.0 * 1024 * 1024, "GB" => 1_000_000_000.0,
            _ => 1.0
        });
    }

    private static TimeSpan? ParseEta(string s)
    {
        if (TimeSpan.TryParse(s, out var t)) return t;
        return null;
    }
}
