using YtDlpTool.Process;
using YtDlpTool.Process.Tests.Helpers;

namespace YtDlpTool.Process.Tests;

public class YtDlpRunnerMetadataTests
{
    [Fact]
    public async Task FetchMetadata_FakeBinary_ReturnsMetadata()
    {
        var runner = new YtDlpRunner(FakeYtDlpLocator.Path());
        var result = await runner.FetchMetadataAsync("https://www.youtube.com/watch?v=FAKE0001234");
        Assert.True(result.IsSuccess, result.ErrorStderr);
        Assert.NotNull(result.Metadata);
        Assert.Equal("FAKE0001234", result.Metadata!.VideoId);
        Assert.Equal("Fake Test Video", result.Metadata.Title);
        Assert.Equal(TimeSpan.FromMinutes(5), result.Metadata.Duration);
        Assert.True(result.Metadata.Formats.Count >= 5);
        Assert.Contains(result.Metadata.Subtitles, s => s.LanguageCode == "en");
        Assert.Contains(result.Metadata.Subtitles, s => s.IsAutoGenerated && s.LanguageCode == "ja");
    }

    [Fact]
    public async Task FetchMetadata_SimulatedError_ReturnsFailure()
    {
        var runner = new YtDlpRunner(FakeYtDlpLocator.Path());
        // The fake exe shortcuts to error mode when --simulate-error is in argv.
        // YtDlpRunner doesn't pass that flag, so to exercise the failure path we pass a URL
        // the fake won't handle — but our fake handles any URL. Instead, simulate by calling
        // ProcessSandbox directly with --simulate-error to confirm stderr propagation.
        var args = new ProcessStartArguments(
            ExecutablePath: FakeYtDlpLocator.Path(),
            Arguments: new[] { "--simulate-error", "403" });
        var exit = await ProcessSandbox.RunAsync(args);
        Assert.Equal(1, exit.ExitCode);
        Assert.Contains("403", exit.Stderr);
    }
}
